services:
  db:
    image: postgres:16-alpine
    container_name: reservas_db
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-reservas_db}
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=64MB"
      - "-c"
      - "effective_cache_size=192MB"
      - "-c"
      - "work_mem=4MB"
      - "-c"
      - "maintenance_work_mem=16MB"
      - "-c"
      - "max_connections=20"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - reservas_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reservas_api
    volumes:
      - ./djangoapi:/app
      - static_volume:/app/static
      - media_volume:/app/media
      - logs_volume:/app/logs
    ports:
      - "${HOST_PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME:-admin}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL:-admin@example.com}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD:-admin}
      - AUTO_POPULATE_DB=${AUTO_POPULATE_DB:-False}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - reservas_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

volumes:
  postgres_data:
    driver: local
  static_volume:
    driver: local
  media_volume:
    driver: local
  logs_volume:
    driver: local

networks:
  reservas_network:
    driver: bridge
